#!/bin/bash
read -p "Enter a string: " str
read -p "Enter the starting index: " start
read -p "Enter the length of the substring: " length
sliced_str=${str:$start:$length}
echo " Sliced string: $sliced_str"
