#!/bin/bash

echo "Prime numbers between 1 to 100 are:"

for ((num=2; num<=100; num++))
do
    # Assume number is prime
    is_prime=1
    
    # Check divisibility from 2 to sqrt(num)
    for ((i=2; i*i<=num; i++))
    do
        if (( num % i == 0 )); then
            is_prime=0
            break
        fi
    done
    
    # If number is still prime, print it
    if (( is_prime == 1 )); then
        echo -n "$num "
    fi
done

echo  # Print a newline at the end

