#!/bin/bash
TARGET_DIR="/path/to/your/folder"


if [ -d "$TARGET_DIR" ]; then
    
    rm -f "$TARGET_DIR"/*
    echo "All files in $TARGET_DIR have been deleted."
else
    echo "Error: Directory $TARGET_DIR does not exist!"
fi
