#!/bin/bash
read -p "Enter a number: " num
original_num=$num
sum=0
while [[ $num -gt 0 ]]; do
    digit=$((num % 10))  # Extract last digit
    sum=$((sum + digit))  # Add to sum
    num=$((num / 10))  # Remove last digit
done
if [[ $((original_num % sum)) -eq 0 ]]; then
    echo " $original_num is a Harshad number!"
else
    echo " $original_num is NOT a Harshad number."
fi


