#!/bin/bash
arr=(24 27 84 11 99)
echo "Given array: ${arr[*]}"

S=100000 
L=0      

# Loop through each element in the array
for num in "${arr[@]}"
do
    if [ "$num" -lt "$S" ]; then
        S=$num
    fi
    if [ "$num" -gt "$L" ]; then
        L=$num
    fi
done
echo "The smallest element: $S"
echo "The largest element: $L"




