#!/bin/bash
read -p "Enter a number: " num
original_num=$num
sum=0
num_digits=${#num}
while [[ $num -gt 0 ]]; do
    digit=$((num % 10))  # Get the last digit
    sum=$((sum + digit**num_digits))  # Add digit^num_digits to sum
    num=$((num / 10))  # Remove the last digit
done
if [[ $sum -eq $original_num ]]; then
    echo " $original_num is an Armstrong number!"
else
    echo " $original_num is NOT an Armstrong number."
fi



