#!/bin/bash
read -p "Enter a number: " num
sum=0
while [[ $num -gt 0 ]]; do
    digit=$((num % 10))  # Get the last digit
    sum=$((sum + digit))  # Add to sum
    num=$((num / 10))  # Remove the last digit
done
echo " Sum of digits: $sum "










